### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: '/home/valerio/datasets/infinitemixer/mfcc_chromo/mapping.pkl'

### ISSUE THREAD

**Issue by Foxy6670** [musikalkemist/infiniteremixer#6]
Whenever I try to run `generate_remix 0.02 64 ./remix.wav`, I always get this error:

`Traceback (most recent call last):                                                  File "/home/pi/infiniteremixer/bin/generate_remix", line 11, in <module>            load_entry_point('infiniteremixer==0.0.1', 'console_scripts', 'generate_remix')()                                                                                 File "/home/pi/infiniteremixer/lib/python3.9/site-packages/infiniteremixer/remix/generateremix.py", line 33, in generate_remix                                        remixer, chunk_merger = _create_objects(jump_rate, num_of_beats)                File "/home/pi/infiniteremixer/lib/python3.9/site-packages/infiniteremixer/remix/generateremix.py", line 43, in _create_objects                                       beats_file_paths = load_from_pickle(MAPPING_PATH)                               File "/home/pi/infiniteremixer/lib/python3.9/site-packages/infiniteremixer/utils/io.py", line 35, in load_from_pickle                                                 with open(load_path, "rb") as file:                                           FileNotFoundError: [Errno 2] No such file or directory: '/home/valerio/datasets/infinitemixer/mfcc_chromo/mapping.pkl'`

How would I go about fixing this?
Thank you in advance!

**Comment by nicholasnadel** [comment]
@Foxy6670 Try opening `/home/pi/infiniteremixer/lib/python3.9/site-packages/infiniteremixer/utils/io.py` and swapping `'/home/valerio/datasets/infinitemixer/mfcc_chromo/mapping.pkl'` with your own path (to wherever `mapping.pkl` exists

If that doesn't solve it, try running `grep -lr "/home/valerio" *` in your infiniteremixer directory to locate  the offending strings
